scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
  BorderZero:
    enabled: false
  ColorKeyword:
    enabled: true
    severity: warning
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
    style: new_line
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
  EmptyRule:
    enabled: true
  FinalNewline:
    enabled: true
    present: true
  HexLength:
    enabled: false
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: true
  ImportantRule:
    enabled: true
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: true
    force_nesting: false
  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase
  NestingDepth:
    enabled: true
    max_depth: 3
  PlaceholderInExtend:
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: true
    extra_properties: []
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false
    severity: warning
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase
  Shorthand:
    enabled: true
    severity: warning
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterVariableName:
     enabled: true
  SpaceAroundOperator:
    enabled: true
    style: one_space
  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false
  SpaceBetweenParens:
    enabled: true
    spaces: 0
  StringQuotes:
    enabled: true
    style: single_quotes
  TrailingSemicolon:
    enabled: true
  TrailingWhitespace:
      enabled: true
  TrailingZero:
    enabled: false
  TransitionAll:
    enabled: false
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VariableForProperty:
    enabled: false
  VendorPrefixes:
    enabled: true
    identifier_list: base
    include: []
    exclude: []
  ZeroUnit:
    enabled: true
    severity: warning
